pipelines:
  default:
    - step:
        name: SonarQube Analysis
        size: 2x
        runs-on:
          - self.hosted
          - linux
        caches:
          - sonar
        script:
          - export SONAR_SCANNER_OPTS="-Xmx2048m"
          - pipe: sonarsource/sonarqube-scan:3.0.2
            variables:
              SONAR_HOST_URL: ${SONAR_HOST_URL}
              SONAR_TOKEN: ${SONAR_TOKEN}
              EXTRA_ARGS: >-
                -Dsonar.projectKey=asset-manager
                -Dsonar.projectName=asset-manager
                -Dsonar.sources=.
                -Dsonar.exclusions=**/node_modules/**,**/dist/**
              DEBUG: "true"

    - step:
        name: Check SonarQube Quality Gate
        size: 2x
        runs-on:
          - self.hosted
          - linux
        script:
          - pipe: sonarsource/sonarqube-quality-gate:1.2.1
            variables:
              SONAR_TOKEN: ${SONAR_TOKEN}
              DEBUG: "true"

    - step:
        name: ASSET-MANAGER
        caches:
          - docker
        services:
          - docker
        script:
          - export IMAGE_NAME=asset-manager:$BITBUCKET_COMMIT
          - docker build -t $IMAGE_NAME .
          - docker tag $IMAGE_NAME asset-manager:latest
          - pipe: atlassian/aws-ecr-push-image:1.0.2
            variables:
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
              IMAGE_NAME: asset-manager
              TAGS: '${BITBUCKET_COMMIT} latest ${BITBUCKET_TAG}'

definitions:
  caches:
    sonar: ~/.sonar
  services:
    docker:
      memory: 3072

clone:
  depth: full

options:
  docker: true