const PharmaConstant = {
    DEVICE_TYPE: "device_type",
    LOCATIONNAME: "locationname",
    SITE_ID: "site_id",
    MODEL_INFO: "model_info",
    MODULE_STATE: "module_state",
    MODULES: "modules",
    M_MODULENAME: "m_moduleName",
    DEVICE_MODEL_ID: "device_model_id",
    MODULE_NAME: "m_moduleName",
    DEVICETYPE: "deviceType",
    DEVICEID: "deviceId",
    MULTI_MODULE_DEVICE_TYPE: "MULTI_MODULE_DEVICE_TYPE",
    ACTION_STATUS: "action_status",
    STATE: "state",
    CHECKED_OUT: "checked-out",
    CHECKED_IN: "checked-in",
    CHECKOUT: "CheckOut",
    CHECKIN: "CheckIn",
    SITE_TIMEZONE: "site_timezone",
    DEVICE_IPS_UPDATE_PERIOD: "DEVICE_IPS_UPDATE_PERIOD",
    DEVICE_IPS_UPDATE_UNIT: "DEVICE_IPS_UPDATE_UNIT",
    M_SENSORID: "m_sensorId",
    SENSOR: "sensor",
    REQUEST_ID: "request_id",
    TEST_EXECUTION_ID: "test_execution_id",
    ACTION_PROCESSING_STATUS: "action_processing_status",
    VIEWED: "VIEWED",
    PARTICLECOUNTER: "particlecounter",
    ORIGIN_TEST_EXECUTION_ID: "origin_test_execution_id",
    PREVIOUS_REQUEST: "previous_request",
    X_CLIENT_ID: "X-Client-id",
    X_REQUESTED_BY: "X-Requested-By",
    LOOKUP_CLIENTS: "lookup_clients",
    DEVICE_TIMEZONE: "device_timezone",
    HEARTBEAT: "heartbeat",
    DEVICE_TIMEZONE_NAME: "device_timezone_name",
    IS_DEFAULT: "is_default",
    DEVICES: "devices",
    INSTRUMENTNAME: "instrumentname",
    LOCATION: "location",
    PHARMA: "PHARMA",
    MERCK: "MERCK",
    PHARMA_DATAHANDLER: "Pharma DataHandler",
    CONNECTED: "Connected",
    DISCONNECTED: "Disconnected",
    UNCONNECTED: "UNCONNECTED",
    COLON: ":",
    PROJECT: "PROJECT",
    MQTT_URL: "MQTT_URL",
    DO_MOCK: "DO_MOCK",
    API_ROOT: "API_ROOT",
    MERCK_PHARMA: "MERCK_PHARMA",
    LOG_VERBOSITY: "LOG_VERBOSITY",
    HEARTBEAT_DELAY_TIME: "HEARTBEAT_DELAY_TIME",
    TLS_ENABLED: "TLS_ENABLED",
    ID: "id",
    SERIALNUMBER: "serialnumber",
    DEVICE: "device",
    SENSOR_ID: "sensorid",
    NETWORK: "network",
    DEVICE_PORT: "deviceport",
    DEVICE_IPADDRESS: "deviceipAddress",
    PICTURE_ID: "picture_id",
    DEVICE_INFO: "deviceinfo",
    ERROR: "error",
    REQUEST: "request",
    DEVICE_ID: "device_id",
    SUCCESS: "success",
    INSTRUMENT_ONBOARDED: "Instrument Onboarded",
    INSTRUMENT_CONNECTED: "Instrument Connected",
    INSTRUMENT_HAS_BEEN_CONNECTED: "Instrument Has Been Connected",
    INSTRUMENT_DISCONNECTED: "Instrument Disconnected",
    INSTRUMENT_HAS_BEEN_DISCONNECTED: "Instrument Has Been Disconnected",
    INSTRUMENT_UPDATED: "Instrument Updated",
    INSTRUMENT_ONBOARDING_FAILED: "Instrument Onboarding Failed",
    DISCOVERY: "DISCOVERY",
    EXTERNAL: "EXTERNAL",
    MQTT_HEARTBEAT_QOS: "MQTT_HEARTBEAT_QOS",
    MQTT_DISCOVERY_QOS: "MQTT_DISCOVERY_QOS",
    MQTT_DISCOVERY_CLIENT_ID: "MQTT_DISCOVERY_CLIENT_ID",
    TO_SAVE: "To Save",
    YES: "yes",
    IS_POLLING: "is_polling",
    ON_BOARDED: "Onboarded",
    UTF8: "UTF-8",
    NAME: "name",
    CREATED_BY: "created_by",
    UPDATED_BY: "updated_by",
    REFERENCE_ID: "reference_id",
    CONNECTION_STATUS: "connection_status",
    GATEWAY_IP: "gateway_ip",
    GATEWAY_TYPE: "gateway_type",
    DISCOVER_TIMESTAMP: "discover_timestamp",
    MODEL_ID: "model_id",
    SERIAL_NUMBER: "serial_number",
    ASSET_ID: "asset_id",
    DEVICE_STATUS: "device_status",
    POLLING_STATUS: "polling_status",
    PORT: "port",
    REPORT_ID: "report_id",
    ADDRESS: "address",
    PATH: "path",
    EVENT_TYPE: "event_type",
    TOPIC: "topic",
    CALIBRATIONDATE: "calibrationdate",
    LAST_CALIBRATION_DATE: "last_calibration_date",
    DEFAULT_MQTT_PORT: 1883,
    DEFAULT_MQTT_TLS_PORT: 8883,
    MODEL_NOT_FOUND_MESSAGE: " Failed to discover device. Model not found!",
    ERROR_CREATING_DEVICE_ASSET_MESSAGE: " Failed to discover device. Error while creating device and asset!",
    DEFAULT_DATE_FORMAT: "yyyy/MM/dd HH:mm:ss",
    MQTT_USERNAME: "MQTT_USERNAME",
    MQTT_PASSWORD: "MQTT_PASSWORD",
    DEACTIVATED: "deactivated",
    DEFAULT_TLS_ENABLED: false,
    CA_FILE_PATH: null,
    CLIENT_CRT_FILE_PATH: null,
    CLINET_KEY_FILE_PATH: null,
    FIRMWAREVERSION: "firmwareversion",
    FIRMWARE_VERSION: "firmware_version",
    DEVICE_DETAILS_UPDATE_PERIOD: "DEVICE_DETAILS_UPDATE_PERIOD",
    DEVICE_DETAILS_UPDATE_UNIT: "DEVICE_DETAILS_UPDATE_UNIT",
    DEVICE_STATUS_UPDATE_PERIOD: "DEVICE_STATUS_UPDATE_PERIOD",
    DEVICE_DISCONNECT_STATUS_UPDATE_PERIOD: "DEVICE_DISCONNECT_STATUS_UPDATE_PERIOD",
    DEVICE_STATUS_UPDATE_UNIT: "DEVICE_STATUS_UPDATE_UNIT",
    DEVICE_DETAILS_UPDATED: "Device details updated",
    DEVICE_TIMEOUT_MSG: "Timeout waiting for response from device",
    COMMENTS: "comments",
    ACTION: "action",
    STOP_POLLING: "Stop_Polling",
    DISCOVERY_API_PORT: "DISCOVERY_API_PORT",
    LOOKUP_DEVICES: "lookup_devices",
    STATUS: "status",
    ACTIVE: "active",
    VERSION: "version",
    PAGINATION: "pagination",
    DATA: "data",
    COUNT: "count",
    TOTALCOUNT: "totalCount",
    CURRENTPAGE: "currentPage",
    MQTT_MSG_THREAD_POOL: "MQTT_MSG_THREAD_POOL",
    MQTT_TOPIC_DATATYPE_HEARTBEAT: "MQTT_TOPIC_DATATYPE_HEARTBEAT",
    MQTT_TOPIC_DATATYPE_DISCOVERY: "MQTT_TOPIC_DATATYPE_DISCOVERY",
    MQTT_TOPIC_DATATYPE_DISCOVERY_RES: "MQTT_TOPIC_DATATYPE_DISCOVERY_RES",
    MQTT_TOPIC_DATATYPE_HANDLER_STATUS_REQ: "MQTT_TOPIC_DATATYPE_HANDLER_STATUS_REQ",
    MQTT_TOPIC_DATATYPE_HANDLER_STATUS_RES: "MQTT_TOPIC_DATATYPE_HANDLER_STATUS_RES",
    MQTT_TOPIC_DATATYPE_ACTION_REQUEST: "MQTT_TOPIC_DATATYPE_ACTION_REQUEST",
    MQTT_TOPIC_DATATYPE_VALIDATE_INTRUMENT_REQ: "MQTT_TOPIC_DATATYPE_VALIDATE_INTRUMENT_REQ",
    MQTT_TOPIC_DATATYPE_VALIDATE_INTRUMENT_RES: "MQTT_TOPIC_DATATYPE_VALIDATE_INTRUMENT_RES",
    MQTT_TOPIC_SEPERATOR: "MQTT_TOPIC_SEPERATOR",
    MQTT_TOPIC_PREFIX: "MQTT_TOPIC_PREFIX",
    DEVICE_IP: "device_ip",
    WIRED: "wired",
    IPADDRESS: "ipaddress",
    DEVICE_TYPE_NAME: "device_type_name",
    DH_REQ_STATUS: "dh_req_status",
    INPROGRESS: "inprogress",
    COMPLETED: "completed",
    META: "meta",
    ERROR_ASSET_NAME_DUPLICATE: 'duplicate key value violates unique constraint "asset_name_key"',
    ERROR_ASSET_ID_DUPLICATE: 'duplicate key value violates unique constraint "asset_asset_id_key"'
};

const ApiConstant = {
    ASSET: "/v1/pm/asset",
    SENSOR: "/v1/sensor",
    REPORT: "/v1/report",
    DEVICE: "/v1/device",
    PROTOCOL: "/v1/protocol",
    ASSET_MODEL: "/v1/pm/asset-model",
    AUDIT_EVENT: "/v1/pm/audit-event",
    DATAHANDLER_STATUS: "/v1/data-handler-status",
    SITE: "/v1/pm/site",
    DEVICE_ID_MODEL_MAPPING: "/v1/device-id-model-mapping",
    SENSOR_MAPPING: "/v1/sensor-mapping",
    DEVICE_ACTION: "/v1/device-action",
    ISDEFAULT: "?is_default:true",
    VALIDATE_INSTRUMENT: "/validate-instrument",
    CLIENTS: "/v1/pm/clients",
    ASSET_TYPE: "/v1/pm/asset-type",
    PM_ASSET_MAPPING: "/v1/pm/asset-id-type-mapping"
}

module.exports = { PharmaConstant, ApiConstant };
