const dotenv = require('dotenv');
dotenv.config();

module.exports = {
  MQTT: {
    URL: process.env.MQTT_URL || 'mqtt://124.123.26.241:1884',
    TOPIC: process.env.MQTT_TOPIC || 'phziot',
    USERNAME: process.env.MQTT_USERNAME || 'merck',
    PASSWORD: process.env.MQTT_PASSWORD || 'merck123',
    CLIENT_ID: process.env.MQTT_CLIENT_ID || 'phizzle',
    QOS: process.env.MQTT_QOS || 0,
    RETAIN: process.env.MQTT_RETAIN || false,
    CLEAN: process.env.MQTT_CLEAN || true,
    KEEPALIVE: process.env.MQTT_KEEPALIVE || 60,
    RECONNECTPERIOD: process.env.MQTT_RECONNECTPERIOD || 1000,
    CONNECTTIMEOUT: process.env.MQTT_CONNECTTIMEOUT || 30 * 1000,
    MQTT_DISCOVERY_CLIENT_ID: process.env.MQTT_DISCOVERY_CLIENT_ID,
    DISCOVERY_QOS: process.env.MQTT_DISCOVERY_QOS,
    HEARTBEAT_QOS: process.env.MQTT_HEARTBEAT_QOS,
    TLS: {
      enable: process.env.TLSENABLED,
      key: '',
      cert: '',
      ca: '',
      host: '',
      port: '',
    }
  },
  TOPIC: {
    // PROGRESS_TOPIC: process.env.PROGRESS_TOPIC || 'phziot/instruments/+/+/heartbeats/progress',
    META_TOPIC: process.env.META_TOPIC || '+/instrument/+/+/heartbeats/meta',
    BASIC_TOPIC: process.env.BASIC_TOPIC || '+/instrument/+/+/heartbeats/basic',
    EM_REQUEST_TOPIC: process.env.EM_REQUEST_TOPIC || '+/instrument/+/heartbeats/emrequest',
    EM_RESPONSE_TOPIC: process.env.EM_RESPONSE_TOPIC || '+/instrument/+/heartbeats/emresponse',
    NOTIFICATION_TOPIC: process.env.NOTIFICATION_TOPIC || '+/instrument/+/+/notification',
    STATUS_TOPIC: process.env.STATUS_TOPIC || 'phziot/instruments/smartplate/C2123088x2030/basic',
    INSTRUMENT_UPDATE_TOPIC: process.env.INSTRUMENT_UPDATE_TOPIC || '+/instrument/+/+/update',
    SEPERATOR: process.env.MQTT_TOPIC_SEPERATOR,
    PREFIX: process.env.MQTT_TOPIC_PREFIX,
  },
  INTERFACES: {
    CLI: true,
    WEB: true,
    MQTT: true,
    API: true
  },
  DEVICE: {
    STATUS_UPDATE_PERIOD: process.env.DEVICE_STATUS_UPDATE_PERIOD,
    STATUS_UPDATE_UNIT: process.env.DEVICE_STATUS_UPDATE_UNIT,
    DETAILS_UPDATE_PERIOD: process.env.DEVICE_DETAILS_UPDATE_PERIOD,
    DETAILS_UPDATE_UNIT: process.env.DEVICE_DETAILS_UPDATE_UNIT,
    IPS_UPDATE_PERIOD: process.env.DEVICE_IPS_UPDATE_PERIOD,
    IPS_UPDATE_UNIT: process.env.DEVICE_IPS_UPDATE_UNIT,
    STATUS_UPDATE_PERIOD_MINS: process.env.DEVICE_STATUS_UPDATE_PERIOD_MINS,
    UPDATE_PERIOD_HRS: process.env.DEVICE_UPDATE_PERIOD_HRS,
    DISCONNECT_STATUS_UPDATE_PERIOD: process.env.DEVICE_DISCONNECT_STATUS_UPDATE_PERIOD,
    DISCONNECT_STATUS_UPDATE_PERIOD_SECONDS: process.env.DEVICE_DISCONNECT_STATUS_UPDATE_PERIOD_SECONDS || 10,
    ASSET_TIME_SYNC_CONFIGURABLE: process.env.ASSET_TIME_SYNC_CONFIGURABLE || 120,
  },
  PROJECT: process.env.PROJECT,
  LOG_VERBOSITY: process.env.LOG_LEVEL,
  API_ROOT: process.env.API_ROOT,
  TLS_ENABLED: process.env.TLS_ENABLED,
  DEFAULT_TLS_ENABLED: process.env.DEFAULT_TLS_ENABLED,
  HEARTBEAT_DELAY_TIME: process.env.HEARTBEAT_DELAY_TIME,
  DISCOVERY_API_PORT: process.env.DISCOVERY_API_PORT,
  MULTI_MODULE_DEVICE_TYPE: process.env.MULTI_MODULE_DEVICE_TYPE,
  MQTT_MSG_THREAD_POOL: process.env.MQTT_MSG_THREAD_POOL,
};
