name: CodeQL + Trivy Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '29 22 * * 1'

permissions:
  contents: read
  security-events: write

jobs:
  trivy_scan:
    name: Trivy Docker Image Scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    needs: analyze
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t docker.io/9492925563/test:${{ github.sha }} .

      - name: Run Trivy scan
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: docker.io/9492925563/test:${{ github.sha }}
          format: sarif
          output: trivy-results.sarif
        env:
          TRIVY_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          TRIVY_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Upload Trivy scan results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-results.sarif
